# Exercise 1
#### Import the NumPy package as np

In [2]:
import numpy as np

# Exercise 2
#### Print the NumPy version and the configuration

In [8]:
print(np.__version__)

1.14.5


In [11]:
np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


# Exercise 3
#### Create a null vector of size 10

In [14]:
Z = np.zeros(10)

In [15]:
Z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# Exercise 4
#### How to get the documentation for the numpy add function from the command line?

python -c "import numpy; numpy.info(numpy.add)"

# Exercise 5
#### Create a null vector of size 10 but the 5th element's value is 1

In [22]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


# Exercise 6
#### Create a vector with values ranging from 10 to 49

In [23]:
Z = np.arange(10, 50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


# Exercise 7
#### Reverse a vector

In [29]:
Z = np.arange(0,10)
Z[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

# Exercise 8
#### Create a 3 x 3 matrix with values ranging from 0 to 8

In [31]:
Z = np.arange(9)
Z.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Exercise 9
#### Find indices of non-zero elements from [1,2,0,0,4,0]

In [37]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


# Exercise 10
#### Create a 3 x 3 identity matrix

In [39]:
Z = np.identity(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [41]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Exercise 11
#### Create a 3 x 3 x 3 array with random values

In [43]:
Z = np.random.rand(3,3,3)
print(Z)

[[[0.34059329 0.3513874  0.43527173]
  [0.56081955 0.54299841 0.10672646]
  [0.90302638 0.08029556 0.81157109]]

 [[0.03105991 0.56638957 0.29884071]
  [0.19725564 0.85900901 0.17177887]
  [0.81323245 0.15434683 0.9219321 ]]

 [[0.33460817 0.71213617 0.21749325]
  [0.03068525 0.44893985 0.06317689]
  [0.55563323 0.33318156 0.42360235]]]


# Exercise 12
#### Create a 10 x 10 array with random values and find the minimum and maximum values

In [48]:
Z = np.random.rand(10,10)
print(np.amin(Z),np.amax(Z))

0.019224764810433004 0.9976642774526597


# Exercise 13
#### Create a random vector of size 30 and find the mean value

In [50]:
Z = np.random.randint(0,100,30).mean()

In [51]:
print(Z)

37.233333333333334


# Exercise 14
#### Create a 2D array with 1 on the border and 0 inside

In [58]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


# Exercise 15
#### What is the result of the following expression?

In [79]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

False

# Exercise 16
#### Create a 5 x 5 matrix with values 1, 2, 3, 4 just below the diagonal

In [86]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# Exercise 17
#### Create an 8 x 8 matrix and fill it with a checkerboard pattern

In [89]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# Exercise 18
#### Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [94]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

# Exercise 19
#### Create a checkerboard 8 x 8 matrix using the tile function

In [95]:
Z = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# Exercise 20
#### Normalize a 5 x 5 random matrix

In [99]:
Z = np.random.random((5,5))
maxZ, minZ = Z.max(), Z.min()
Z = (Z - maxZ) / (maxZ -minZ)
print(Z)

[[-0.73585808 -0.84080643 -0.19746289 -0.3517885  -0.92103519]
 [-0.81303762 -0.99069647 -0.78125157 -0.3124492  -0.40515061]
 [-0.71593512 -0.26384404 -0.43814915  0.         -0.65993392]
 [-0.77188122 -0.55351974 -0.43906675 -1.         -0.07651471]
 [-0.74296674 -0.98457804 -0.9312258  -0.61612325 -0.8637517 ]]


# Exercise 21
#### Create a custom data type that describes a color as four unassigned bytes (RGBA)

In [107]:
color = np.dtype([("r", np.ubyte, 1)
                 ,("g", np.ubyte, 1)
                 ,("b", np.ubyte, 1)
                 ,('a', np.ubyte, 1)])

In [108]:
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [109]:
color = [1,2,3,4]

In [110]:
color

[1, 2, 3, 4]

# Exercise 22
#### Multiply a 5 x 3 matrix by a 3 x 2 matrix (real matrix product)

In [113]:
Z = np.dot(np.ones((5,3)),np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


# Exercise 23
#### Given a 1D array, negate all elements which are between 3 and 8, in place

In [117]:
Z = np.arange(11)
Z[(Z > 3) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


# Exercise 24
#### What is the output of the following script?

In [119]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


# Exercise 25
#### Consider an integer vector Z, which of these expressions are legal?

In [121]:
Z = np.arange(5)
print(Z)

[0 1 2 3 4]


In [122]:
Z ** Z

array([  1,   1,   4,  27, 256])

In [123]:
2 << Z >> 2

array([0, 1, 2, 4, 8])

In [124]:
Z <- Z

array([False, False, False, False, False])

In [125]:
j = np.arange(2)

In [126]:
1j * Z

array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j])

In [127]:
Z / 1 / 1

array([0., 1., 2., 3., 4.])

In [128]:
Z <Z> Z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

# Exercise 26
#### What are the results of the following expressions?

In [130]:
np.array(5) // np.array(5)

1

In [131]:
np.array(5) // np.array(5.)

1.0

In [132]:
np.array(5) / np.array(5)

1.0

In [133]:
np.array(5) / np.array(5.)

1.0

# Exercise 27
#### How to round away from zero in a float array?

In [138]:
Z = np.random.uniform(-10,+10,10)
print(Z)
print(np.trunc(Z + np.copysign(0.5,Z)))

[ 9.59224339 -4.11551339 -1.76556199  3.81428758  2.79664452  5.68089515
  5.87282719  8.75304481 -2.72098361  7.74819256]
[10. -4. -2.  4.  3.  6.  6.  9. -3.  8.]


# Exercise 28
#### Extract the integer part of a random array using 5 different methods

In [142]:
Z = np.random.uniform(10,0,10)
print(Z)

[8.59927384 0.95656604 5.98487375 7.92411781 8.00979973 8.91549454
 1.39958411 5.73260159 2.14158562 6.99962131]


In [151]:
Z - Z % 1

array([8., 0., 5., 7., 8., 8., 1., 5., 2., 6.])

In [153]:
np.floor(Z)

array([8., 0., 5., 7., 8., 8., 1., 5., 2., 6.])

In [154]:
np.ceil(Z)-1

array([8., 0., 5., 7., 8., 8., 1., 5., 2., 6.])

In [155]:
Z.astype(int)

array([8, 0, 5, 7, 8, 8, 1, 5, 2, 6])

In [156]:
np.trunc(Z)

array([8., 0., 5., 7., 8., 8., 1., 5., 2., 6.])

# Exercise 29
#### Create a 5 x 5 matrix with row values ranging from 0 to 4

In [158]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
