In [1]:
arr.arange(20)

NameError: name 'arr' is not defined

In [2]:
import numpy as np

In [4]:
arr = np.arange(20)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [29]:
arr.reshape(4, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [8]:
arr2 = arr.reshape((4, 5))

In [9]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [10]:
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [11]:
arr2[1:]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [14]:
arr2[1, 3]

8

In [15]:
arr2[0:1]

array([[0, 1, 2, 3, 4]])

In [23]:
np.mean(arr2[0:2])

4.5

In [26]:
np.mean(arr2[1:3, 1:4])

9.5

In [32]:
arr = np.arange(20).reshape(4, -1)

In [33]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [34]:
np.arange(20).reshape(4,-1)[1:3,1:4].mean()

9.5

In [35]:
arr = np.arange(20)

In [36]:
arr[arr > 7]

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [37]:
(arr > 7).dtype

dtype('bool')

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [41]:
arr[[1, 3, 5, -1]]

array([ 1,  3,  5, 19])